name: ci

on:
  push:
    branches:
      - master
      - dev

jobs:

  tests:
    name: Building, testing, and pushing images
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
         
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      run: |-
        cd Pipeline1 && docker build -t nminocha/pipeline-1:${{  github.sha }} .
        docker push nminocha/pipeline-1:${{  github.sha }} && cd ../
        cd Pipeline2 && docker build -t nminocha/pipeline-2:${{  github.sha }} .
        docker push nminocha/pipeline-2:${{  github.sha }}
